version: "3.3"

services:

  server:
    build: ./backend
    volumes:
      - "./backend:/srv/server"
    environment:
      DJANGO_SETTINGS_MODULE: "backend.settings.dev"
    command: >
      uwsgi
        --socket 0.0.0.0:8000
        --master
        --processes 1
        --threads 4
        --python-autoreload 1
        --wsgi-file ./backend/wsgi.py

  nginx:
    ports:
      - "80:80"
    environment:
      COMMENT_EXPIRES: "#"